name: Build Docker and publish

on:
  push:
    branches:
      - master
      - feature/add-docker-support
    tags:
      - v2.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: rbongers/certbot-dns-transip
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
